language: ruby
rvm:
  - 2.3.1
env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
before_install:
 - sudo apt-get -y update
 - sudo apt-get -y install libpq-dev
before_script:
  # ensure the test output and coverage dirs are created
  - mkdir -p shippable/testresults
  - bin/rails db:environment:set RAILS_ENV=test
script:
  - rspec -f RspecJunitFormatter -o shippable/testresults/results.xml
  - rubocop
cache: true
